=== JosefHook/genfoo/Src/xml/operator.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema 
   xmlns:xs="http://www.w3.org/2001/XMLSchema" 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   elementFormDefault="qualified">
  

  <xs:complexType name="stringVector">
    <xs:sequence>
      <xs:element name="value" type="xs:string" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="index" type="xs:integer" use="required"/>
  </xs:complexType>

  <xs:complexType name="stringMatrix">
    <xs:sequence>
      <xs:element name="value" type="xs:string" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="indexColumn" type="xs:integer" use="required"/>
    <xs:attribute name="indexRow" type="xs:integer" use="required"/>
  </xs:complexType>

  <xs:element name="Operator">
    <xs:annotation>
      <xs:documentation>
Fokker-Planck/Monte Carlo operator for GenFoo.
Allows the user to supply algebraic expressions for the drift, diffusion and source using C syntax.

/author Josef Hook and Thomas Johnson
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:all>

	<xs:element name="Documentation" type="xs:string" minOccurs="0">
	  <xs:annotation>
	    <xs:documentation>For documentation of the operator.</xs:documentation>
	  </xs:annotation>
	</xs:element>

	<xs:element name="Dimensions" type="xs:integer" minOccurs="1" maxOccurs="1">
	  <xs:annotation>
	    <xs:documentation>Number of dimensions.</xs:documentation>
	  </xs:annotation>
	</xs:element>

	<xs:element name="Drift" minOccurs="0" maxOccurs="1">
	  <xs:annotation>
	    <xs:documentation>Monte Carlo drift, e.g. x[0]^2 -2*x[1]</xs:documentation>
	  </xs:annotation>
	  <xs:complexType>
	    <xs:sequence>
	      <xs:element name="code" type="xs:string" minOccurs="0"/>
	      <xs:element name="component" type="stringVector" minOccurs="0" maxOccurs="unbounded"/>
	    </xs:sequence>
	  </xs:complexType>
	</xs:element>

	<xs:element name="Diffusion" minOccurs="0" maxOccurs="1">
	  <xs:annotation>
	    <xs:documentation>Diffusion, e.g. x[0]^2 -2*x[1]</xs:documentation>
	  </xs:annotation>
	  <xs:complexType>
	    <xs:sequence>
	      <xs:element name="code" type="xs:string" minOccurs="0"/>
	      <xs:element name="component" type="stringMatrix" minOccurs="0" maxOccurs="unbounded"/>
	    </xs:sequence>
	  </xs:complexType>
	</xs:element>

	<xs:element name="Source" minOccurs="0" maxOccurs="1">
	  <xs:annotation>
	    <xs:documentation>Source, e.g. x[0]^2 -2*x[1]</xs:documentation>
	  </xs:annotation>
	  <xs:complexType>
	    <xs:sequence>
	      <xs:element name="code" type="xs:string" minOccurs="0"/>
	      <xs:element name="value" type="xs:string" minOccurs="0"/>
	    </xs:sequence>
	  </xs:complexType>
	</xs:element>

	<xs:element name="InitialCondition" minOccurs="1" maxOccurs="1">
	  <xs:annotation>
	    <xs:documentation>InitialCondition, e.g. x[0]^2 -2*x[1]</xs:documentation>
	  </xs:annotation>
	  <xs:complexType>
	    <xs:sequence>
	      <xs:element name="code" type="xs:string" minOccurs="0"/>
	      <xs:element name="value" type="xs:string" minOccurs="0"/>
	    </xs:sequence>
	  </xs:complexType>
	</xs:element>
	
	<xs:element name="Include" minOccurs="0" maxOccurs="unbounded">
	  <xs:annotation>
	    <xs:documentation>Include libraries</xs:documentation>
	  </xs:annotation>
	  <xs:complexType>
	    <xs:all>
	      <xs:element name="libraryName" type="xs:string"  minOccurs="0" maxOccurs="unbounded"/>
	    </xs:all>
	  </xs:complexType>
	</xs:element>

	<xs:element name="Private" minOccurs="0" maxOccurs="1">
	  <xs:annotation>
	    <xs:documentation>List of variables and methods that can be used in the operator</xs:documentation>
	  </xs:annotation>
	  <xs:complexType>
	    <xs:sequence>

	      <xs:element name="variable" minOccurs="0" maxOccurs="unbounded">
		<xs:annotation>
		  <xs:documentation>Definition of local variables that can be used in the operator</xs:documentation>
		</xs:annotation>
		<xs:complexType>
		  <xs:all>
		    <xs:element name="name"          type="xs:string"  minOccurs="1"/>
		    <xs:element name="value"         type="xs:string"  minOccurs="0"/>
		    <xs:element name="documentation" type="xs:string"  minOccurs="0"/>
		  </xs:all>
		  <xs:attribute name="static" type="xs:boolean"/>
		  <xs:attribute name="const"  type="xs:boolean"/>
		  <xs:attribute name="type"   type="xs:string" use="required"/>
		  <xs:attribute name="isVector" type="xs:boolean" use="optional" default="false"/>
		  <xs:attribute name="unit"   type="xs:string" use="optional"/>
		</xs:complexType>
	      </xs:element>

	      <xs:element name="function" minOccurs="0" maxOccurs="unbounded">
		<xs:complexType>
		  <xs:all>
		    <xs:element name="documentation" type="xs:string"  minOccurs="0"/>
		    <xs:element name="name"       type="xs:string" minOccurs="1"/>
		    <xs:element name="input"      type="xs:string" minOccurs="0"/>
		    <xs:element name="code"       type="xs:string" minOccurs="0"/>
		  </xs:all>
		  <xs:attribute name="type" type="xs:string" use="required"/>
		  <xs:attribute name="unit" type="xs:string"/>
		</xs:complexType>
	      </xs:element>

	    </xs:sequence>
	  </xs:complexType>
	</xs:element>
      </xs:all>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== JosefHook/genfoo/Operators/XML/Stix1DModel.xml
<?xml version="1.0" encoding="UTF-8"?>
<Operator
   xmlns:xs="http://www.w3.org/2001/XMLSchema"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="operator.xsd">

  <Documentation>
ICRF and collisionoperator. 
UNDER DEVELOPMENT!

Coordinates:
- x[0] the Energy normalised to the on axis temperature of the simulated species.
  </Documentation>

    <Private>
       <variable type="double" static="true" const="true">
          <documentation> static param</documentation>
          <name> eps0 </name>
          <type> double </type>
	  <value>  8.8542e-12 </value>
	  <unit> 1 </unit>
       </variable>

       <variable type="int" static="true" const="true">
          <documentation>Simulated species</documentation>
          <name>  indexSimulatedSpecies </name>
	  <value> 2 </value>
       </variable>
       <variable type="double" static="true" const="true" unit="kg" isVector="true">
          <documentation> Masses of all plasma species</documentation>
          <name> mass </name>
	  <value> 9.1e-31, 2.0*1.6726e-27 , 3.0*1.6726e-27 , 4.0*1.6726e-27</value>
       </variable>
       <variable type="double" static="true" const="true" unit="C" isVector="true">
          <documentation>Charges of all plasma species</documentation>
          <name> charge </name>
	  <value> -1.0*1.6022e-19 , 1.0*1.6022e-19 , 1.0*1.6022e-19 , 2.0*1.6022e-19</value>
       </variable>
       <variable type="double" static="true" const="true" unit="m**-3" isVector="true">
          <documentation>Densities of all plasma species</documentation>
          <name>density</name>
	  <value> 1.06e20 , 0.5e20 , 0.5e20 , 3.0e18 </value>
       </variable>
       <variable type="double" static="true" const="true" unit="J" isVector="true">
          <documentation> Temperatures of all plasma species</documentation>
          <name> temperature </name>
	  <value> 20.0e3*1.6022e-19 , 20.0e3*1.6022e-19 , 20.0e3*1.6022e-19 , 20.0e3*1.6022e-19 </value>
       </variable>
       <variable type="double" static="true" const="true" unit="T">
          <documentation>Magnetic field at the magnetic axis</documentation>
          <name> B0 </name>
	  <value> 5.6 </value>
       </variable>
       <variable type="double" static="true" const="true" unit="m">
          <documentation>Major radius at the magnetic axis</documentation>
          <name> R0 </name>
	  <value> 7.5 </value>
       </variable>
       <variable type="double" static="true" const="true" unit="m">
          <documentation>Minor radius</documentation>
          <name> aminor </name>
	  <value> 7.5/3.0 </value>
       </variable>
       <variable type="double" static="true" const="true" unit="m">
          <documentation>Larmor radius</documentation>
          <name> rhoLarmor </name>
	  <value> 0.01 </value>
       </variable>
       <variable type="double" static="true" const="true" unit="V/m">
          <documentation>Toroidal electric field</documentation>
          <name> Etoroidal </name>
	  <value> 1e-4 </value>
       </variable>
       <variable type="double" static="true" const="true" unit="T">
          <documentation>Poloidal magnetic field</documentation>
          <name> Bpoloidal </name>
	  <value> 0.2 </value>
       </variable>
       <variable type="double" static="true" const="true" unit="Hz">
          <documentation>ICRF wave frequency</documentation>
          <name> ICfrequency </name>
	  <value> 65e6 </value>
       </variable>
       <variable type="double" static="true" const="true" unit="V/m">
          <documentation>ICRF wave, E-field amplitude</documentation>
          <name> ICEplus </name>
	  <value> 2000.0 </value>
       </variable>
       <variable type="double" static="true" const="true" unit="1/m">
          <documentation>ICRF wave kperp</documentation>
          <name> ICkperp </name>
	  <value> 20.0 </value>
       </variable>
       <variable type="double" static="true" const="true">
          <documentation>ICRF wave, harmonic number of interaction </documentation>
          <name> ICnHarmonic </name>
	  <value> 2.0 </value>
       </variable>

<!--
========================================================================
FUNCTIONS: 
========================================================================
-->
       <function type="double">
          <documentation>Check if species j is the electron species</documentation>
          <name> isElectron </name>
	  <code>
	    return mass[j] &lt; 1.0e-27 ? 1 : 0;
	  </code>
	  <input> int j </input>
       </function>

       <function type="double">
          <documentation>Electron Density</documentation>
          <name> electronDensity </name>
	  <code>
    for (int j=0;j &lt; mass.size() ; j++){
      if ( isElectron(j) ){
        return density[j];
      }
    }
    return 0.0;
    </code>
       </function>
       <function type="double">
          <documentation>Effective Charge</documentation>
          <name> Zeff </name>
	  <code>
    double nz2=0.0;
    for (int j=0;j &lt; charge.size() ; j++){
      if ( not(isElectron(j)) ){
       nz2 += density[j]*std::pow(charge[j],2);
      }
    }
    return nz2 / (1.6022e-19*electronDensity());
    </code>
       </function>

       <function type="double">
          <documentation>Thermal velocity</documentation>
          <name> velocityThermal </name>
	  <code> 

	    return std::sqrt(2.0*temperature[indexSpeices]/mass[indexSpeices]);</code>
	  <input>int indexSpeices</input>
       </function>

       <function type="double">
          <documentation>Thermal ion larmor radius at the magneitc axis</documentation>
          <name> rhoLarmorThermalAtAxis </name>
	  <code> return charge[indexSpeices] * B0 / (mass[indexSpeices] * velocityThermal(indexSpeices));</code>
	  <input>int indexSpeices</input>
       </function>

       <function type="double">
          <documentation>Coloumb Logarithm</documentation>
          <name>coloumbLogarithm</name>
	  <code>
   double lnT = std::log(temperature[indexSpeices]/1.6022e-19/1e3);
   double lnDens = std::log(electronDensity()/1e20);

//cout  &lt;&lt; "lnL = "  &lt;&lt; 17.3 - 0.5*lnDens + 1.5*lnT &lt;&lt; endl;

//   return 20.0; 

   if (isElectron(indexSpeices)){
     return 15.2 - 0.5*lnDens + lnT;
   } else {
     return 17.3 - 0.5*lnDens + 1.5*lnT;
   }
</code>
	  <input>int indexSpeices</input>
       </function>

       <function type="double">
          <documentation>Function G(x) defined in Stix, page 509</documentation>
          <name> Stix_G </name>
	  <code> 
   double phi = 1.0-erfc(x);
//cout &lt;&lt; "x="  &lt;&lt; x  &lt;&lt; " erf="  &lt;&lt; phi  &lt;&lt; endl;
   double phiPrime= exp(-x*x)*2.0/sqrt(M_PI);
   return (phi - x * phiPrime) / (2.0*x*x);
</code>
	  <input>double x</input>
       </function>

       <function type="double">
          <documentation>Collision parameter Cf (related to the collision frequency) defined in Stix, page 508</documentation>
          <name> Stix_Cf </name>
	  <code>

// p1=q/m
// p2=Z*logL
// p3=q/eps0
// p4=np*q/eps0
// p5=ne*q/eps0

// (8.0*M_PI*p2*std::pow(Ze,2))*(p1*p5)*(p1*p3)/( std::pow(4.0*M_PI,2))

    return (0.5/(M_PI*std::pow(eps0,2))) * density[jf] * std::pow(charge[j]*charge[jf]/mass[j],2)* coloumbLogarithm(jf);
	  </code>
	  <input>int j, int jf</input>
       </function>

       <function type="double">
          <documentation>Chandrasekar collision frequency alpha_f, defined in Stix on page 508</documentation>
          <name> Stix_alpha_f </name>
	  <code>
    double vth=velocityThermal(jf);
    double vthSim=velocityThermal(indexSimulatedSpecies);
    double x=(v+1e-6*vthSim)/vth;
    double G=Stix_G(x);
    double C=Stix_Cf(j,jf);
    return (C/(vth*vth)) * (1.0-mass[j]/mass[jf]) * G;
	  </code>
	  <input> double v, int j, int jf </input>
       </function>

       <function type="double">
          <documentation>Chandrasekar collision frequency beta_f, defined in Stix on page 508</documentation>
          <name> Stix_beta_f </name>
	  <code>
    double vth=velocityThermal(jf);
    double vthSim=velocityThermal(indexSimulatedSpecies);
    double vNon0=v+1e-6*vthSim;
    double x=vNon0/vth;
    double G=Stix_G(x);
    double C=Stix_Cf(j,jf);
//  cout   &lt;&lt; "Stix_beta_f: "   &lt;&lt; x  &lt;&lt; " "  &lt;&lt; j*100+jf  &lt;&lt; " C="  &lt;&lt; G*C/v &lt;&lt; endl; 
    return (C/vNon0) * G;
	  </code>
	  <input> double v, int j, int jf </input>
       </function>

       <function type="double">
          <documentation>Chandrasekar collision frequency gamma_f, defined in Stix on page 508</documentation>
          <name> Stix_gamma_f </name>
	  <code>
    double vth=velocityThermal(jf);
    double vthSim=velocityThermal(indexSimulatedSpecies);
    double vNon0=v+1e-6*vthSim;
    double x=vNon0/vth;
    double G=Stix_G(x);
    double phi=1.0-erfc(x);
    double C=Stix_Cf(j,jf);
//cout   &lt;&lt; "HERE: "   &lt;&lt;  phi  &lt;&lt; "  "  &lt;&lt;  G &lt;&lt; endl;

    return (C/v) * (phi-G);
	  </code>
	  <input> double v, int j, int jf </input>
       </function>

       <function type="double">
          <documentation>Chandrasekar collision frequency alpha, defined in Stix on page 508</documentation>
          <name> Stix_alpha </name>
	  <code>
    double fun=0.0;

    for (int jf=0;jf &lt; charge.size() ; jf++){
    fun += Stix_alpha_f(v,j,jf);

    }
    return fun;
    </code>
	  <input> double v, int j</input>
       </function>

       <function type="double">
          <documentation>Chandrasekar collision frequency beta, defined in Stix on page 508</documentation>
          <name> Stix_beta </name>
	  <code>
    double fun=0.0;
    for (int jf=0;jf &lt; charge.size() ; jf++){
      fun += Stix_beta_f(v,j,jf);

    }
    return fun;
    </code>
	  <input> double v, int j</input>
       </function>

       <function type="double">
          <documentation>Chandrasekar collision frequency gamma, defined in Stix on page 508</documentation>
          <name> Stix_gamma </name>
	  <code>
